import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Footer } from './components/footer';


=======
>>>>>>> 92e5b24 (Carousel)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Ereceita",
  description: "Um site dedicado a receitas deliciosas, práticas e cheias de sabor para todos os momentos.",
  icons: {
    icon:"/favicon.ico",
  }
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 92e5b24 (Carousel)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
<<<<<<< HEAD

        <Footer></Footer>
=======
>>>>>>> 92e5b24 (Carousel)
      </body>
    </html>
  );
}
